name: my-build 
on:
  push:
    branches: master
jobs:
  print_hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello, world!"
        
  maven_clean:
    runs-on: ubuntu-latest
    needs: [print_hello]
    
    steps:
    - name: Maven Package
      run: mvn -B clean 
